title = "Pier"

[port]
http = {{.HttpPort}}
pprof = {{.PprofPort}}

[log]
level = "info"
dir = "logs"
filename = "pier.log"
report_caller = false

[mode]
type = "{{.Mode}}" # relay, direct or union
[mode.relay]
addr = "{{.Bitxhub}}"
quorum = 2
validators = [
    {{.Validators}}
]
[mode.direct]
peers = [{{.Peers}}]

[mode.union]
connectors = [{{.Connectors}}]
providers = {{.Providers}}

[security]
enable_tls = {{.Tls}}
tlsca = "certs/ca.pem"
common_name = "localhost"

[appchain]
plugin = "{{.PluginFile}}"
config = "{{.PluginConfig}}"
