title = "Pier"

[port]
http = {{.HttpPort}}
pprof = {{.PprofPort}}

[log]
level = "info"
dir = "logs"
filename = "pier.log"
report_caller = false
[log.module]
  api_server   = "info"
  appchain_mgr = "info"
  bxh_lite     = "info"
  executor     = "info"
  exchanger    = "info"
  monitor      = "info"
  peer_mgr     = "info"
  router       = "info"
  rule_mgr     = "info"
  swarm        = "info"
  syncer       = "info"

[mode]
type = "{{.Mode}}" # relay, direct or union
[mode.relay]
addr =  "{{.Bitxhub}}"
quorum = 2
validators = [
    {{.Validators}}
]
[mode.direct]
peers = [{{.Peers}}]

[mode.union]
connectors = [{{.Connectors}}]
providers = {{.Providers}}

[security]
enable_tls = {{.Tls}}
tlsca = "certs/ca.pem"
common_name = "localhost"

[HA]
mode = "single"

[appchain]
plugin = "{{.PluginFile}}"
config = "{{.PluginConfig}}"
